language: node_js
node_js:
  - "10"

# Turns on newer container-based infrastructure
# This generates a sudo warning with mongodb below, see here: https://github.com/travis-ci/travis-ci/issues/3044
sudo: required


# We have `npm ci` errors, so force it to use `npm install`
install:
  - true


script:
  - cat package-lock.json
  - rm package-lock.json
  - npm install
  - cat package-lock.json

notifications:
  email: false
