language: node_js
node_js:
  - "10"

# Turns on newer container-based infrastructure
# This generates a sudo warning with mongodb below, see here: https://github.com/travis-ci/travis-ci/issues/3044
sudo: required


# We have `npm ci` errors, so force it to use `npm install`
install:
  - true

before_install:
  # Install dependencies for node `canvas` package
  # https://github.com/Automattic/node-canvas#compiling
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++


script:
  - npm ci --verbose

notifications:
  email: false
